services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=ContactsUser
      - POSTGRES_PASSWORD=ContactsPassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    restart: always
    container_name: redis
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
volumes:
  postgres:
  redis:
